#!/usr/bin/env python3
"""Derive the site's product imagery from the master photos in `photos/`.

Run after dropping new/updated master shots into `photos/`:

    pip install -r requirements-dev.txt
    python build_images.py

Everything under `static/img/products/` is generated by this script — treat
those files as build output, not as things to hand-edit. `photos/` is the
source of truth.

Two silhouettes, handled differently because the source photography differs:

* Clover Pillow Bag (shoulderbag) — four separately photographed colourways
  on a white studio background. Copied through, re-encoded only.

* Clover Bubble Bag (crossbody) — only ONE exterior was ever photographed (the
  cream shell, identical across all four source PNGs; those PNGs differ only
  in their interior lining). Shipping four listings that all show the same
  cream bag made the colourways indistinguishable in any grid, so the front
  and back views are recoloured per colourway: hue+saturation are taken from
  the lining colour while each pixel's original brightness is preserved, so
  the shading, seams and highlights of the real photograph survive.
  The interior shot is the genuine per-colourway photo, cropped as-is.

Note: the homepage hero (`static/img/home/hero-lifestyle.jpg`) is a separate
lifestyle photograph that is used unmodified and is NOT built here.
"""
import colorsys
import os

import numpy as np
from PIL import Image, ImageChops, ImageDraw, ImageFilter, ImageOps

ROOT = os.path.dirname(os.path.abspath(__file__))
PHOTOS = os.path.join(ROOT, "photos")
OUT = os.path.join(ROOT, "static", "img", "products")
OUT_HOME = os.path.join(ROOT, "static", "img", "home")

JPEG_QUALITY = 92

# ── Clover Bubble Series banner ────────────────────────────────────────────
#
# The master is a marketing sheet: a baked-in title, then the four-bag lineup
# with colourway labels, then a strip of interior shots. Only the lineup band
# is used — the site supplies its own heading as real text, so the baked-in
# title is cropped away rather than shipped as an image of words.
# Bottom edge stops at 674: the colourway labels end at y≈635 and the interior
# detail strips begin at y≈677, so this keeps the labels with clearance while
# leaving the strips out.
SERIES_MASTER = "Clover Bubble Series.jpg"
SERIES_BAND = (0, 255, 1536, 674)

# The flat backdrop tone at the top of that band. `--bubble-banner-bg` in
# pages.css must match, so the section colour and the photo meet invisibly.
SERIES_BACKDROP = (245, 237, 231)  # #F5EDE7

# The Pillow lineup, used inside the Clover Collection tile. Unlike the Bubble
# banner this sits as a discrete rounded image on a coloured card, so it needs
# no backdrop fade — just the band cropped to the four bags.
PILLOW_SERIES_MASTER = "Clover Pillow Series.jpg"
PILLOW_SERIES_BAND = (0, 250, 1448, 1010)

# The Bubble Bag master. All four "round clover *.png" files show the same cream
# exterior, so the exterior only needs reading from one of them.
BUBBLE_MASTER = "Round clover baby blue .png"

# Crop boxes within the Bubble Bag master sheet (which is a multi-panel layout:
# front / back / lining swatch on top, interior shots below).
BUBBLE_FRONT_BOX = (15, 10, 585, 410)
BUBBLE_BACK_BOX = (615, 10, 1165, 410)
BUBBLE_INTERIOR_BOX = (10, 495, 555, 900)

# The master sheet's panels sit on a light backdrop, but a strip of the studio
# floor is visible between the crossed straps. It keys out as semi-transparent
# and would otherwise show up as a grey smear once composited, so it is painted
# out to the backdrop colour *before* keying.
BUBBLE_FLOOR_PATCH = {"front": (110, 330, 470, 400), "back": (95, 330, 455, 400)}
BUBBLE_BACKDROP = (245, 244, 242)

# Background-key thresholds: pixels at/above `hi` brightness are fully
# transparent, at/below `lo` fully opaque, linear in between.
BUBBLE_KEY = (228, 241)

# design_code -> (source png for the interior shot, recolour target RGB)
#
# The recolour target is the *lining* colour, so the shell matches the inside.
# Sage is deliberately richer than its raw lining swatch (#AFB19F), which is
# too desaturated to read as green once applied across a whole bag.
BUBBLE_COLOURWAYS = {
    "bubbleblue": ("Round clover baby blue .png", (183, 199, 214)),
    "bubblelavender": ("round clover pastel lavender.png", (205, 185, 210)),
    "bubblepink": ("round clover pastel pink.png", (215, 170, 169)),
    "bubblesage": ("round clover sage green.png", (150, 172, 128)),
}

# design_code -> source photo. These are shot as-is, no compositing needed.
PILLOW_COLOURWAYS = {
    "babyblue": "Baby Blue Clover Handbag.jpg",
    "black": "Black Clover Handbag.jpg",
    "dustypink": "Dusty pink Clover Handbag.jpg",
    "mintgreen": "Mint Green Clover Handbag.jpg",
}


def _paint_out(im, box, rgb, blur=10):
    """Blend `box` out to a flat colour with a soft edge."""
    patch = Image.new("RGB", im.size, rgb)
    mask = Image.new("L", im.size, 0)
    ImageDraw.Draw(mask).rectangle(box, fill=255)
    return Image.composite(patch, im, mask.filter(ImageFilter.GaussianBlur(blur)))


def _key_out_background(im, lo, hi, erode=2, blur=1.4):
    """Alpha-key a light studio background out, returning RGBA.

    Uses the per-pixel minimum channel as a "whiteness" measure, so a bright
    but saturated pixel (part of the product) is kept while a neutral bright
    one (the backdrop) is dropped. Eroding before the feather pulls the matte
    just inside the product edge, which avoids a pale halo when the cut-out is
    later composited onto white.
    """
    im = im.convert("RGB")
    r, g, b = im.split()
    whiteness = ImageChops.darker(ImageChops.darker(r, g), b)
    scale = 255.0 / (hi - lo)
    alpha = whiteness.point([max(0, min(255, round((hi - v) * scale))) for v in range(256)])
    if erode:
        alpha = alpha.filter(ImageFilter.MinFilter(erode * 2 + 1))
    if blur:
        alpha = alpha.filter(ImageFilter.GaussianBlur(blur))
    out = im.convert("RGBA")
    out.putalpha(alpha)
    return out


def _trim(im):
    bbox = im.split()[-1].getbbox()
    return im.crop(bbox) if bbox else im


def _recolour(rgba, target_rgb):
    """Repaint an RGBA cut-out in `target_rgb`, keeping its original shading.

    Every pixel takes the target's hue and saturation but keeps its own HSV
    value, so folds, seams, shadows and specular highlights all survive.
    """
    arr = np.array(rgba).astype(np.float32) / 255.0
    r, g, b, a = arr[..., 0], arr[..., 1], arr[..., 2], arr[..., 3]
    v = np.maximum(np.maximum(r, g), b)

    hue, sat, _ = colorsys.rgb_to_hsv(*[c / 255.0 for c in target_rgb])

    # Inlined HSV->RGB so it runs over the whole array at once.
    i = np.floor(np.full_like(v, hue) * 6.0)
    f = np.full_like(v, hue) * 6.0 - i
    p = v * (1.0 - sat)
    q = v * (1.0 - f * sat)
    t = v * (1.0 - (1.0 - f) * sat)
    sel = [(i.astype(int) % 6) == n for n in range(6)]

    out = np.stack([
        np.select(sel, [v, q, p, p, t, v]),
        np.select(sel, [t, v, v, q, p, p]),
        np.select(sel, [p, p, t, v, v, q]),
        a,
    ], axis=-1)
    return Image.fromarray(np.clip(out * 255, 0, 255).astype(np.uint8), "RGBA")


def _save_on_white(rgba, path):
    canvas = Image.new("RGB", rgba.size, (255, 255, 255))
    canvas.paste(rgba, (0, 0), rgba)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    canvas.save(path, quality=JPEG_QUALITY)
    print(f"  wrote {os.path.relpath(path, ROOT)}")


def build_bubble_bags():
    print("Clover Bubble Bag (crossbody)")
    master = Image.open(os.path.join(PHOTOS, BUBBLE_MASTER))

    cutouts = {}
    for view, box in (("front", BUBBLE_FRONT_BOX), ("back", BUBBLE_BACK_BOX)):
        panel = master.crop(box).convert("RGB")
        panel = _paint_out(panel, BUBBLE_FLOOR_PATCH[view], BUBBLE_BACKDROP)
        cutouts[view] = _trim(_key_out_background(panel, *BUBBLE_KEY))

    for code, (interior_src, target) in BUBBLE_COLOURWAYS.items():
        dest = os.path.join(OUT, "signature", "clover", code)
        for view, cut in cutouts.items():
            _save_on_white(_recolour(cut, target), os.path.join(dest, f"{view}.jpg"))

        interior = Image.open(os.path.join(PHOTOS, interior_src))
        interior = interior.crop(BUBBLE_INTERIOR_BOX).convert("RGB")
        os.makedirs(dest, exist_ok=True)
        interior.save(os.path.join(dest, "interior.jpg"), quality=JPEG_QUALITY)
        print(f"  wrote {os.path.relpath(os.path.join(dest, 'interior.jpg'), ROOT)}")


def build_series_banner():
    """Crop the Bubble Series lineup out of the marketing sheet.

    The top rows are faded to the backdrop colour so the photo has no visible
    upper edge: dropped onto a section painted the same colour, it reads as one
    continuous surface running up behind the heading, rather than a picture
    pasted into the page.
    """
    print("Clover Bubble Series banner")
    band = Image.open(os.path.join(PHOTOS, SERIES_MASTER)).convert("RGB").crop(SERIES_BAND)

    fade_h = 90
    flat = Image.new("RGB", (band.width, fade_h), SERIES_BACKDROP)
    # linear_gradient runs black->white top-to-bottom; inverted it is opaque at
    # the very top (all backdrop) easing to transparent (all photo) by fade_h.
    ramp = ImageOps.invert(Image.linear_gradient("L")).resize((1, fade_h)).resize((band.width, fade_h))
    band.paste(flat, (0, 0), ramp)

    os.makedirs(OUT_HOME, exist_ok=True)
    dest = os.path.join(OUT_HOME, "clover-bubble-series.jpg")
    band.save(dest, quality=JPEG_QUALITY)
    print(f"  wrote {os.path.relpath(dest, ROOT)}")


def build_pillow_series_tile():
    """Crop the Pillow lineup for the Clover Collection tile."""
    print("Clover Pillow Series tile")
    band = (Image.open(os.path.join(PHOTOS, PILLOW_SERIES_MASTER))
            .convert("RGB").crop(PILLOW_SERIES_BAND))
    os.makedirs(OUT_HOME, exist_ok=True)
    dest = os.path.join(OUT_HOME, "clover-pillow-series.jpg")
    band.save(dest, quality=JPEG_QUALITY)
    print(f"  wrote {os.path.relpath(dest, ROOT)}")


def build_pillow_bags():
    print("Clover Pillow Bag (shoulderbag)")
    for code, src in PILLOW_COLOURWAYS.items():
        dest = os.path.join(OUT, "cosy", "pillow", code, "hero.jpg")
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        Image.open(os.path.join(PHOTOS, src)).convert("RGB").save(dest, quality=JPEG_QUALITY)
        print(f"  wrote {os.path.relpath(dest, ROOT)}")


if __name__ == "__main__":
    build_bubble_bags()
    build_pillow_bags()
    build_series_banner()
    build_pillow_series_tile()
    print("\nDone. Run `python seed.py` if any image paths changed.")
