"""add bag_type to product

Revision ID: 8c7f52bc6d06
Revises: e557096b3155
Create Date: 2026-04-26 09:42:40.637677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7f52bc6d06'
down_revision = 'e557096b3155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bag_type', sa.String(length=40), nullable=False, server_default='tote'))
        batch_op.create_index(batch_op.f('ix_products_bag_type'), ['bag_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_bag_type'))
        batch_op.drop_column('bag_type')

    # ### end Alembic commands ###
