"""product merchandising fields + product_images

Revision ID: e557096b3155
Revises: 82845e4901e5
Create Date: 2026-04-26 09:30:47.128263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e557096b3155'
down_revision = '82845e4901e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('alt', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_hex', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('tile_eyebrow', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('tile_headline', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tile_body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=False, server_default='100'))
        batch_op.create_index(batch_op.f('ix_products_design_code'), ['design_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_design_code'))
        batch_op.drop_column('display_order')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('tile_body')
        batch_op.drop_column('tile_headline')
        batch_op.drop_column('tile_eyebrow')
        batch_op.drop_column('color_hex')

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    op.drop_table('product_images')
    # ### end Alembic commands ###
